server:
  # Config Service 应用所监听的端口
  port: 8888
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    # 当前应用的名称
    name: config-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
  cloud:
    config:
      server:
        git:
          # 远程 Git 仓库的 URL，用作配置数据的后端
          uri: https://github.com/wyx151425/config-repo
          # 默认情况下，服务器将会在 main 分支返回配置数据
          default-label: main
          # 与远程仓库建立连接的时间限制
          timeout: 5
          # 在启动的时候，克隆远程仓库到本地
          clone-on-start: true
          # 强制拉取远程仓库并废弃本地变更
          force-pull: true
          skip-ssl-validation: true
